### ISSUE TITLE
[Question]: specify allowed origins (cors)

### ISSUE THREAD

**Issue by anime-kun32** [moonlitgrace/mangareader-api#492]
um i managed to deploy the api , but now how do i add allowed origins

**Comment by moonlitgrace** [comment]
hey @anime-kun32, that's great!
can you take a look at this [docs](https://fastapi.tiangolo.com/tutorial/cors/) abt cors? it is explained well.
lmk if you need any other help.

**Comment by anime-kun32** [comment]
Ok I understand I have to use cors middlewar now the question is do I make a new file to include it or edit a file if so what file do I have to edit

**Comment by moonlitgrace** [comment]
hey @anime-kun32, I made some changes, update your fork.
you can specify your origins here:
https://github.com/moonlitgrace/mangareader-api/blob/9aa42010a72b25b1c35954d13da94834ff682977/main.py#L37-L40
make sure to remove that wildcard pattern (`*`)

**Comment by anime-kun32** [comment]
thanks
